name: lidar-env
channels:
  - defaults
dependencies:
  - python=3.11
  - matplotlib
  - numpy
  - pandas
  - scipy
  - ipykernel
  - scikit-learn
  - notebook
  - ipympl
  - pip
  - pip:
      - open3d
